### ISSUE TITLE
Re-Implement Features using In-Browser Storage

### ISSUE THREAD

**Issue by TrueKuehli** [TrueKuehli/PruneTree#1]
The goal of this project is to replace the API of the original Plum Tree app with local browser storage. This allows hosting the project without a dedicated server, since only static assets need to be served. To accomplish this, the following tasks need to be performed:

## Tasks
- [x] Replace the primary API interface for trees and people with the IndexedDB API
- [x] Allow uploading and storing of images in the IDB
- [x] Read the remaining storage quota and show in the sidebar and on the creation site for new trees / people
- [x] Show a warning when creating a new tree / person and the storage quota reaches a specific threshold (e.g. 50%)
- [x] Catch storage quota errors in the database calls

**Comment by TrueKuehli** [comment]
Closed by cce18df06fa27e122926d4f18f00209ea700d85b
