### ISSUE TITLE
Improve the Person Linker Feature

### ISSUE THREAD

**Issue by TrueKuehli** [TrueKuehli/PruneTree#11]
Providing dropdown menus for easily choosing a tree and person to link to would improve usability of the feature a lot.

## Tasks
- [ ] Add a dropdown menu to choose another tree to link to
- [ ] Add a dropdown menu to choose a person to link to
- [ ] Add a feature to import a person from another tree instead of having to recreate them

One problem with the linker feature as a whole is the fact that IDs are not maintained when exporting / importing a tree / person. As a result, even importing the same trees as provided by the creator will not restore the links between people in them. 

My initial idea to resolve this is to add a hidden UUID which is included on export. This way, the linker could instead use these UUIDs to prevent links from breaking as long as all relevant trees are imported.

## Tasks
- [ ] Add hidden UUID on person / tree database entry
- [ ] Use this ID internally for generating links; the user should still only see the "normal" ID however, as large UUIDs would result in really ugly URLs
