### ISSUE TITLE
Migrate CI

### ISSUE THREAD

**Issue by TrueKuehli** [TrueKuehli/PruneTree#5]
The Gitlab Continuous Integration scripts should be migrated over to GitHub actions.

## Tasks
- [x] Set up GitHub actions
- [x] Migrate test and build scripts
- [x] Set up GitHub pages
- [x] Create a new deploy script to deploy directly to GitHub pages
- [x] Update `TODO.md` to reflect the changes to the CI pipeline
