### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by TrueKuehli** [TrueKuehli/PruneTree#7]
Since the fork, some dependencies are now left unused. Additionally, I want to change the code style to something I'm more familiar with, leading to the following migration efforts.

## Tasks
- [x] Remove unused depencies
- [x] Migrate to TypeScript
- [x] Replace `standard` linter with `eslint` (probably using the Google Code Style)
