### ISSUE TITLE
Re-Implement Download Feature and allow Importing/Exporting Trees

### ISSUE THREAD

**Issue by TrueKuehli** [TrueKuehli/PruneTree#8]
The downloading feature previously relied on the server. Instead we want to generate all resources locally now.

## Tasks
- [x] Allow downloading of a tree and associated people as a JSON file (This should be a good first step; it works as a proof of concept to locally generating the files and will later be reused for importing)
- [x] Implement a feature to import previously exported JSON files
- [x] Implement a feature to import Plum Tree downloads
- [ ] Re-Implement the original HTML export in the browser
- [ ] Consider adding an image export, if this can easily be achieved

**Comment by TrueKuehli** [comment]
For the image export feature, we could consider using https://github.com/canvg/canvg, if our trees render correctly using that.

**Comment by TrueKuehli** [comment]
For the import feature, a really nice addition would also be to allow users to upload their old Plum Tree downloads. This may require some additional work to match up the data structures more nicely, and there's no guarantee that it would work at all.

From what I've seen the data for trees and people is split into different javascript files. These could be uploaded separately with a quick check for whether the people match the references found in the tree (and showing a warning if this is not the case. I'll have to have a closer look at these scripts to determine if we want to provide such an import feature.

**Comment by TrueKuehli** [comment]
Something to also consider is the idea of providing cloud backups using e.g. Google Drive. This way users could log in using their Google account and trees can be stored, including a timestamp corresponding to the backup. That way we can restore that cloud backup if the user either loses their device, or even synchronize the trees across multiple devices.

Of course this feature would be optional and the main storage location would still be in the user's browser. However, since browser storage is by it's very nature not very persistent, loss of data can only be avoided using backups. Local backups as suggested in the main issue are a good first step, but may be too impractical for some users.

**Comment by TrueKuehli** [comment]
In regard to the original HTML output, we may want to investigate providing an alternate "database" implementation that simply offers read access to some JSON file / literal JS object. This way we could provide a version of the tree viewer component of the app with all assets bundled into one (monstrous) HTML file (assuming this doesn't cause some issues on very large trees; alternatively a small number of static files), with editing disabled.

We could then produce this file as a secondary compile target (optimally without any additional files to prevent duplication), into which we insert a placeholder for the "database" object. This object could then dynamically be added in the browser on the download page to prepare the downloaded tree.

This is still pretty vague, so some things might not work as described here and I may have missed some things. Once I have some clearer ideas I will turn this into it's own issue.
